## Common auth demo properties

server:
  address: localhost
  port: 8080

spring:

#  exaxmple mail config for google mail
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: email@gmail.com
#    password: apikey
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

#   in order to use this demo project with mysql database:
#   uncomment lines below, and comment out h2 related lines below
#   run create-db.sh
#   uncomment contents of DbIdentityFixConfig.java


#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:6603/authDemoDb?useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: mypassword
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  h2.console.path: /h2-console

  # JSON serialization settings
  jackson:
    default-property-inclusion: NON_NULL

    serialization:
      write-null-map-values: false

    deserialization:
      accept-single-value-as-array: true


  # https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding
  main.allow-bean-definition-overriding: true

server.servlet.session.persistent: false

rapid-core:
  applicationUrl: http://127.0.0.1:8080

rapid-auth:

  # ADMIN users
  admins:
    - contactInformation: admin@example.com
      password: AdminPassword123!
    - contactInformation: secondAdmin@example.com
      password: SecondAdminPassword123!

  # Properties to be passed to client
  shared:
    fooBar: 123...

  jwt:
      # An aes-128-cbc key generated at https://asecuritysite.com/encryption/keygen (take the "key" field)
    secret: 841D8A6C80CBA4FCAD32D5367C18C53B
    expiration-millis: 864000000 # 10 days
    short-lived-millis: 120000   # two minutes