## Common auth demo properties

server:
  address: localhost
  port: 8080

spring:

#  exaxmple mail config for google mail
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: email@gmail.com
#    password: apikey
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  h2.console.path: /h2-console

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

rapid-core:
  applicationUrl: http://127.0.0.1:8080

rapid-auth:

  # ADMIN users
  admins:
    - contactInformation: admin@example.com
      password: AdminPassword123!
    - contactInformation: secondAdmin@example.com
      password: SecondAdminPassword123!

  jwt:
      # An aes-128-cbc key generated at https://asecuritysite.com/encryption/keygen (take the "key" field)
    secret: 841D8A6C80CBA4FCAD32D5367C18C53B
    expiration-millis: 864000000 # 10 days
    short-lived-millis: 120000   # two minutes