spring:

  # Active profile
  profiles.active: dev,service,web

  jpa:
    hibernate:
      ddl-auto: create

#   in order to use this demo project with mysql database:
#   uncomment lines below, and comment out h2 related lines below
#   run create-db.sh
#   uncomment contents of DbIdentityFixConfig.java


#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:6603/aclDemoDb?useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: mypassword
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  h2.console.path: /h2-console

rapid-auth:

  # ADMIN users
  admins:
    - contactInformation: admin@example.com
      password: AdminPassword123!

  jwt:
      # An aes-128-cbc key generated at https://asecuritysite.com/encryption/keygen (take the "key" field)
    secret: 841D8A6C80CBA4FCAD32D5367C18C53B
    expiration-millis: 864000000 # 10 days
    short-lived-millis: 120000   # two minutes