spring:

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  h2.console.path: /h2-console

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

rapid-auth:

  # ADMIN users
  create-admins: false

  jwt:
      # An aes-128-cbc key generated at https://asecuritysite.com/encryption/keygen (take the "key" field)
    secret: 841D8A6C80CBA4FCAD32D5367C18C53B
    expiration-millis: 864000000 # 10 days
    short-lived-millis: 120000   # two minutes